### ISSUE TITLE
[Bug] Exception ticking world

### ISSUE THREAD

**Issue by angushushu** [CubeX-MC/CubeX#116]
**描述**
```
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:889)
	at com.google.common.collect.ImmutableSet.construct(ImmutableSet.java:204)
	at com.google.common.collect.ImmutableSet.constructUnknownDuplication(ImmutableSet.java:170)
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:243)
	at net.minecraft.world.entity.ai.attributes.AttributeInstance.getModifiers(AttributeInstance.java:57)
	at net.minecraft.network.protocol.game.ClientboundUpdateAttributesPacket.<init>(ClientboundUpdateAttributesPacket.java:23)
	at net.minecraft.server.level.ServerEntity.sendDirtyEntityData(ServerEntity.java:384)
	at net.minecraft.server.level.ServerEntity.sendChanges(ServerEntity.java:205)
	at net.minecraft.server.level.ChunkTracker.processTrackQueue(ChunkTracker.java:1267)
	at net.minecraft.server.level.ChunkTracker.tick(ChunkTracker.java:1278)
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:829)
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:652)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:707)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1564)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
导致服务器崩溃

**预期行为**
不应该出现

**附加内容**
好像除了MythicMobs没有涉及修改AI的插件，但是每次崩溃都没有玩家在资源世界MythicMobs应该没被使用。打算先禁用MythicMobs几天观察一下，如果还是有就考虑升级1.19.4. 插件在本地试过一次目前没发现问题。

**Comment by FallenCrystal** [comment]
我在曾经就说过这个问题了 这**应该**是Purpur的bug.

> 不要使用任何被修改的服务端 而是使用原生Paper ——计划在1.19.4


> 关于1.19.4?

实际上我目前并没有那么多时间测试 多等一个月我放假了再说吧

**Comment by angushushu** [comment]
OK
