### ISSUE TITLE
[update] MoeBungeeChat替代essentialsx chat

### ISSUE THREAD

**Issue by angushushu** [CubeX-MC/CubeX#122]
**描述**
换用MoeBungeeChat作为聊天插件绕过聊天举报

**任务清单**
- [ ] 构建MoeBungeeChat

**补充**
目前构建时有个依赖问题不到咋解决：
```
for project catmoe.fallencrystal:MoeBungeeChat:jar:0.1: Could not find artifact catmoe.fallencrystal.moefilter:MoeFilter:jar:0.0.4 in sonatype (https://oss.sonatype.org/content/groups/public/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by FallenCrystal** [comment]
使用`mvn install`构建MoeFilter

**Comment by FallenCrystal** [comment]
因未响应被标记为解决 如果需要 再次打开问题即可

**Comment by angushushu** [comment]
加到BC后蹦出个异常：
```

[01:40:21 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@52d3fafd, id=137, owner=catmoe.fallencrystal.moebungeechat.MoeBungeeChat@1f7853af, task=catmoe.fallencrystal.moebungeechat.chat.ChatListener$$Lambda$1913/0x0000000801acc000@30e03d16, delay=0, period=0, running=true) encountered an exception
java.lang.NoSuchMethodError: 'void catmoe.fallencrystal.moefilter.util.message.v2.MessageUtil.sendMessage(java.lang.String, catmoe.fallencrystal.moefilter.util.message.v2.packet.type.MessagesType, net.md_5.bungee.api.connection.ProxiedPlayer)'
        at catmoe.fallencrystal.moebungeechat.chat.ChatListener.onChat$lambda$3(ChatListener.kt:61) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:57) ~[NullCordX-3.7.6.jar:1.20-R0.1-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]

```

**Comment by FallenCrystal** [comment]
> 有个问题，装在BC的MoeBungeeChat怎么调后端的玩家工会名？

尝试自定义他们的prefix 并将bc和后端的LuckPerms连起来 否则没有别的办法 我目前不会在此项目上做太多事 我在给MoeFilter写Limbo.

**Comment by FallenCrystal** [comment]
补充:
 - prefix应该设置在LuckPerms内部的 如果能使用命令 你可以通过命令来做到这点

> 将玩家通过命令给予prefix

 - bc和后端的LuckPerms连起来 : 我的意思是 用sql
